### ISSUE TITLE
It is not working with latest react version 18.2.0

### ISSUE THREAD

**Issue by prince17dec** [dkress59/react-loading-icons#10] opened 2022-09-13 10:02 UTC
I tried to install it with react 18 and seems like it is not supported.

**Comment by dkress59** [comment] 2022-09-13 10:38
@prince17dec I'm using it myself with react v18.2.0 and react ^18.0.0 is listed as a [peer dependency](https://github.com/dkress59/react-loading-icons/blob/master/package.json#L12)

can you give me some more input on what seems to be the issue (e.g. console logs)?
are you using it with typescript or without?

**Comment by prince17dec** [comment] 2022-09-13 12:40
I did not get any errors in the console. but yes am using the typescript with react.

**Comment by dkress59** [comment] 2022-09-13 16:43
well, you'll have to offer me some kind of insight, if you want me to help you.

how are you importing the icon(s)? do you mind sharing your source code? are they maybe there, but just have no width/height, or are transparent? the fill/stroke properties default to `currentColor` (the text color of the containing HTMLElement).

**Comment by dkress59** [comment] 2022-09-15 07:34
@prince17dec do you have an update?

**Comment by dkress59** [comment] 2022-09-22 12:23
closing this issue, cannot reproduce. seems like a non-issue.

**Closed as not planned by dkress59** 2022-09-22 12:23 UTC
